# Change 'comments' to true for Disqus comments
disqus:

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menu:
- {name: 'About', path: 'menu', url: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'goodreads', link: 'https://www.goodreads.com/user/show/65674597-alex-miao'}
- {icon: 'github', link: 'https://www.github.com/alex-miao'}
- {icon: 'twitter', link: 'https://twitter.com/alexsmiao'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/alex-miao/'}

site:
  paginate: false

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

post_date_prefix: 'Written on'
